.TH HELLO "1" "January 2021" "hello 1.0.0" "User Commands"
.SH NAME
hello \- Print a Hello, world! message
.SH SYNOPSIS
.B hello
.SH DESCRIPTION
.PP
Print a Hello, world! message to stdout.
.SS "Exit status:"
.TP
0
in all cases
.SH EXAMPLES
.TP
.B "hello"
This will print the Hello, world! message to stdout.
.SH AUTHOR
Christian Hujer (Christian.Hujer@nelkinda.com), Nelkinda Software Craft Pvt Ltd.
.SH "REPORTING BUGS"
Report bugs to <https://github.com/christianhujer/hello-c>
.SH COPYRIGHT
Copyright \(co 2021 Christian Hujer.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Full documentation at: <https://github.com/christianhujer/hello-c>
.br
or available locally via: man hello
